#!/usr/bin/env python
# -*- coding: utf-8 -*-

def checkInside(sw,ne, lat, lon):
	s,w =[float(x.strip()) for x in sw.split(',')]
	n,e =[float(x.strip()) for x in ne.split(',')]
	return (lon <=n and lon >=s) and (lat <=e and lat >=w)

swBound = '55.857278, 37.744596'
neBound = '55.868067, 37.761419'

print checkInside(swBound,neBound,55.8827729059,37.7317704369)
